version: '3'
services:
  mariadb:
    image: mariadb:10.11
    container_name: moodle-db
    environment:
      MYSQL_ROOT_PASSWORD: moodlepass
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - moodle-network

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle-app
    ports:
      - "4324:8080"
    environment:
      MOODLE_DATABASE_TYPE: mariadb
      MOODLE_DATABASE_HOST: mariadb
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: moodleuser
      MOODLE_DATABASE_PASSWORD: moodlepass
      MOODLE_DATABASE_NAME: moodle
      MOODLE_SKIP_BOOTSTRAP: "no"
      # Desactivar SSL en el cliente MySQL/MariaDB
      MYSQL_CLIENT_DISABLE_SSL: "true"
    depends_on:
      - mariadb
    volumes:
      - moodle_data:/bitnami/moodle
      - moodle_moodledata:/bitnami/moodledata
      - ./theme/suayed:/bitnami/moodle/theme/suayed
    networks:
      - moodle-network

volumes:
  mariadb_data:
  moodle_data:
  moodle_moodledata:

networks:
  moodle-network:
    driver: bridge
